# Heart Disease Prediction and Risk Assessment Using Machine Learning on Clinical Health Data

## Phase 1: Data Collection and Understanding

### Objective

The objective of this phase is to collect the heart disease dataset, understand its structure, identify the available features, examine data types, and perform an initial exploration of the dataset before preprocessing.

This phase helps in understanding the quality of the data and prepares it for the subsequent preprocessing and machine learning stages.

## Step 1.1 Import Required Libraries

Import the essential Python libraries required for data manipulation, visualization, and exploratory analysis.

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

## Step 1.2 Load the Dataset

Load the processed cardiovascular disease dataset into a pandas DataFrame for analysis.

In [2]:
df = pd.read_csv("../data/raw/cardio_data_processed.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

## Step 1.3 Display the Dataset

Display the first five and last five observations to understand the structure of the dataset.

In [3]:
print("First 5 records:")
display(df.head())

print("Last 5 records:")
display(df.tail())

First 5 records:

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50,21.967120,Hypertension Stage 1,Hypertension Stage 1
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55,34.927679,Hypertension Stage 2,Hypertension Stage 2
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,51,23.507805,Hypertension Stage 1,Hypertension Stage 1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48,28.710479,Hypertension Stage 2,Hypertension Stage 2
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,47,23.011177,Normal,Normal

Last 5 records:

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,age_years,bmi,bp_category,bp_category_encoded
68200,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0,52,26.927438,Hypertension Stage 1,Hypertension Stage 1
68201,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1,61,50.472681,Hypertension Stage 2,Hypertension Stage 2
68202,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1,52,31.353579,Hypertension Stage 2,Hypertension Stage 2
68203,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1,61,27.099251,Hypertension Stage 1,Hypertension Stage 1
68204,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0,56,24.913495,Hypertension Stage 1,Hypertension Stage 1

## Step 1.4 Check Dataset Dimensions

Determine the total number of rows and columns present in the dataset.

In [4]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 68205
Columns : 17

## Step 1.5 Display Feature Names

List all the features available in the dataset.

In [5]:
df.columns.tolist()

['id',
 'age',
 'gender',
 'height',
 'weight',
 'ap_hi',
 'ap_lo',
 'cholesterol',
 'gluc',
 'smoke',
 'alco',
 'active',
 'cardio',
 'age_years',
 'bmi',
 'bp_category',
 'bp_category_encoded']

## Step 1.6 Dataset Information

Display information about the dataset, including data types, number of non-null values, and memory usage.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68205 entries, 0 to 68204
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   68205 non-null  int64
 1   age                  68205 non-null  int64
 2   gender               68205 non-null  int64
 3   height               68205 non-null  int64
 4   weight               68205 non-null  float64
 5   ap_hi                68205 non-null  int64
 6   ap_lo                68205 non-null  int64
 7   cholesterol          68205 non-null  int64
 8   gluc                 68205 non-null  int64
 9   smoke                68205 non-null  int64
 10  alco                 68205 non-null  int64
 11  active               68205 non-null  int64
 12  cardio               68205 non-null  int64
 13  age_years            68205 non-null  int64
 14  bmi                  68205 non-null  float64
 15  bp_category          68205 non-null  object
 16  bp_category_encoded  68205 non-null  object
dtypes: float64(2), int64(13), object(2)
memory usage: 8.8+ MB

## Step 1.7 Statistical Summary

Generate descriptive statistics for all numerical features to understand their distributions.

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,68205.0,49972.410498,28852.138290,0.000000,24991.000000,50008.000000,74878.000000,99999.000000
age,68205.0,19462.667737,2468.381854,10798.000000,17656.000000,19700.000000,21323.000000,23713.000000
gender,68205.0,1.348625,0.476539,1.000000,1.000000,1.000000,2.000000,2.000000
height,68205.0,164.372861,8.176756,55.000000,159.000000,165.000000,170.000000,250.000000
weight,68205.0,74.100688,14.288862,11.000000,65.000000,72.000000,82.000000,200.000000
ap_hi,68205.0,126.434924,15.961685,90.000000,120.000000,120.000000,140.000000,180.000000
ap_lo,68205.0,81.263925,9.143985,60.000000,80.000000,80.000000,90.000000,120.000000
cholesterol,68205.0,1.363243,0.678080,1.000000,1.000000,1.000000,1.000000,3.000000
gluc,68205.0,1.225174,0.571288,1.000000,1.000000,1.000000,1.000000,3.000000
smoke,68205.0,0.087662,0.282805,0.000000,0.000000,0.000000,0.000000,1.000000
alco,68205.0,0.053134,0.224302,0.000000,0.000000,0.000000,0.000000,1.000000
active,68205.0,0.803548,0.397317,0.000000,1.000000,1.000000,1.000000,1.000000
cardio,68205.0,0.493688,0.499964,0.000000,0.000000,0.000000,1.000000,1.000000
age_years,68205.0,52.823635,6.769909,29.000000,48.000000,53.000000,58.000000,64.000000
bmi,68205.0,27.510513,6.026497,3.471784,23.875115,26.346494,30.116213,298.666667

## Step 1.8 Check Data Types

Display the data type of each feature in the dataset.

In [8]:
df.dtypes

id                       int64
age                      int64
gender                   int64
height                   int64
weight                 float64
ap_hi                    int64
ap_lo                    int64
cholesterol              int64
gluc                     int64
smoke                    int64
alco                     int64
active                   int64
cardio                   int64
age_years                int64
bmi                    float64
bp_category             object
bp_category_encoded     object
dtype: object

## Step 1.9 Identify Numerical and Categorical Features

Separate the dataset into numerical and categorical features for better understanding.

In [9]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

categorical_columns = df.select_dtypes(include=["object", "category"]).columns.tolist()

print("Numerical Features")
print(numerical_columns)

print()

print("Categorical Features")
print(categorical_columns)

Numerical Features
['id', 'age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active', 'cardio', 'age_years', 'bmi']

Categorical Features
['bp_category', 'bp_category_encoded']

## Step 1.10 Explore Target Variable

Display the distribution of the target variable (`cardio`) to understand the class balance.

In [10]:
df["cardio"].value_counts()
df["cardio"].value_counts(normalize=True) * 100

cardio
0    50.631185
1    49.368815
Name: proportion, dtype: float64

## Step 1.11 Check Missing Values

Identify missing values in the dataset.

In [11]:
df.isnull().sum()

id                     0
age                    0
gender                 0
height                 0
weight                 0
ap_hi                  0
ap_lo                  0
cholesterol            0
gluc                   0
smoke                  0
alco                   0
active                 0
cardio                 0
age_years              0
bmi                    0
bp_category            0
bp_category_encoded    0
dtype: int64

## Step 1.12 Check Duplicate Records

Identify duplicate observations in the dataset.

In [12]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

# Phase Summary

### Observations

- The dataset was successfully loaded.
- The dataset dimensions were examined.
- Feature names and data types were identified.
- Statistical summaries of numerical variables were generated.
- The target variable distribution was explored.
- Missing values and duplicate records were checked.

The dataset understanding phase is now complete and the data is ready for preprocessing in the next phase.